data_cfg:
  dataset_name: OUMVLP
  dataset_root: your_path
  dataset_partition: ./datasets/OUMVLP/OUMVLP.json
  num_workers: 1
  remove_no_gallery: false
  test_dataset_name: OUMVLP

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 210000
  save_name: GaitGS_OUMVLP
  sampler:
    batch_size: 4
    sample_type: all_ordered
    frames_all_limit: 720

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.25
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 16 
    type: CrossEntropyLoss
    log_accuracy: true
    log_prefix: softmax
  - loss_term_weight: 0.2
    scale: 1
    type: CrossEntropyLoss
    log_accuracy: true
    label_smooth: false
    log_prefix: view_softmax

model_cfg:
  model: GaitGS_OUMVLP
  channels: [32, 64, 128, 256]
  view_num: 14
  parts_num: 32
  depth: 3
  kernel_size: 7
  num_head: 8
  out_dim: 256
  class_num: 5153

optimizer_cfg:
  lr: 1.0e-4
  solver: Adam
  weight_decay: 5.0e-4

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 150000
    - 200000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true
  with_test: false
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 1000
  save_name: GaitGS_OUMVLP
  sync_BN: true
  total_iter: 210000
  sampler:
    batch_shuffle: true
    batch_size:
      - 32
      - 8
    frames_num_fixed: 30
    frames_skip_num: 0
    sample_type: fixed_ordered
    type: TripletSampler